export const FETCH_CHATS_REQUEST = "FETCH_CHATS_REQUEST";

export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";

export const FETCH_CHATS_FAILURE = "FETCH_CHATS_FAILURE";

export const FETCH_MESSAGES_REQUEST = "FETCH_MESSAGES_REQUEST";

export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";

export const FETCH_MESSAGES_FAILURE = "FETCH_MESSAGES_FAILURE";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";

export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";


export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";

export const FETCH_CHAT_FAILURE = "FETCH_CHAT_FAILURE";

export const RECEIVE_MESSAGE_SUCCESS = "RECEIVE_MESSAGE_SUCCESS";

export const ADD_MESSAGE = "ADD_MESSAGE";

export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";


export const LEAVE_CHAT_SUCCESS = "LEAVE_CHAT_SUCCESS";

export const LEAVE_CHAT_FAILURE = "LEAVE_CHAT_FAILURE";