
export const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST";
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAILURE = "ADD_GROUP_FAILURE";

export const EDIT_GROUP_REQUEST = "EDIT_GROUP_REQUEST";
export const EDIT_GROUP_SUCCESS = "EDIT_GROUP_SUCCESS";
export const EDIT_GROUP_FAILURE = "EDIT_GROUP_FAILURE";

export const SET_GROUP_AVATAR = "SET_GROUP_AVATAR";

export const KICK_USER_REQUEST = "KICK_USER_REQUEST";
export const KICK_USER_SUCCESS = "KICK_USER_SUCCESS";
export const KICK_USER_FAILURE = "KICK_USER_FAILURE";


export const ADD_USER_TO_CHAT_REQUEST = "ADD_USER_TO_CHAT_REQUEST";
export const ADD_USER_TO_CHAT_SUCCESS = "ADD_USER_TO_CHAT_SUCCESS";
export const ADD_USER_TO_CHAT_FAILURE = "ADD_USER_TO_CHAT_FAILURE";
