
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const SIGNUP = "SIGNUP";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNUP_FAILURE = "SIGNUP_FAILURE";


export const SEARCH_USERS_REQUEST = "SEARCH_USERS_REQUEST";

export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";

export const SEARCH_USERS_FAILURE = "SEARCH_USERS_FAILURE";