export const SIGNUP = "SIGNUP";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNUP_FAILURE = "SIGNUP_FAILURE";


export const SEARCH_USERS_REQUEST = "SEARCH_USERS_REQUEST";

export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";

export const SEARCH_USERS_FAILURE = "SEARCH_USERS_FAILURE";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";


export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const ADD_USER = "ADD_USER";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";

export const SET_USER_AVATAR = "SET_USER_AVATAR";

