
export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CLEAN_LOGIN_ERRORS = "CLEAN_LOGIN_ERRORS";

export const LOGOUT = "LOGOUT";

export const SIGNUP = "SIGNUP";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNUP_FAILURE = "SIGNUP_FAILURE";


export const SEARCH_USERS_REQUEST = "SEARCH_USERS_REQUEST";

export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";

export const SEARCH_USERS_FAILURE = "SEARCH_USERS_FAILURE";

export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const ADD_USER = "ADD_USER";
